<?php include 'includes/header.php';
$stats=$conn->query("SELECT COUNT(*) items, COALESCE(SUM(boh+total_received+total_returned-total_issued),0) stock, COALESCE(SUM(total_issued),0) issued, COALESCE(SUM(total_returned),0) returned, COALESCE(SUM(total_received),0) received FROM items")->fetch_assoc();
$months=$conn->query("SELECT DATE_FORMAT(created_at,'%Y-%m') m, action_type, SUM(quantity) q FROM transactions GROUP BY m, action_type ORDER BY m DESC LIMIT 18");
$labels=[];$rec=[];$iss=[];$ret=[]; while($r=$months->fetch_assoc()){ if(!in_array($r['m'],$labels))$labels[]=$r['m']; if($r['action_type']=='Received')$rec[$r['m']]=$r['q']; if($r['action_type']=='Issued')$iss[$r['m']]=$r['q']; if($r['action_type']=='Returned')$ret[$r['m']]=$r['q']; }
$low=$conn->query("SELECT *,(boh+total_received+total_returned-total_issued) stock FROM items WHERE (boh+total_received+total_returned-total_issued)<=reorder_level ORDER BY stock ASC LIMIT 10"); ?>
<div class='row g-3 mb-4'><div class='col-md-3'><div class='stat'><small>Total Stock</small><h3><?=$stats['stock']?></h3></div></div><div class='col-md-3'><div class='stat orange'><small>Issued</small><h3><?=$stats['issued']?></h3></div></div><div class='col-md-3'><div class='stat green'><small>Received</small><h3><?=$stats['received']?></h3></div></div><div class='col-md-3'><div class='stat red'><small>Returned</small><h3><?=$stats['returned']?></h3></div></div></div>
<div class='row g-3'><div class='col-lg-8'><div class='card cardx p-4'><h5>Monthly Analytics</h5><canvas id='monthlyChart'></canvas></div></div><div class='col-lg-4'><div class='card cardx p-4'><h5>Real-time Low Stock</h5><div class='table-responsive'><table class='table table-sm'><tr><th>Item</th><th>Stock</th></tr><?php while($i=$low->fetch_assoc()): ?><tr class='<?= $i['stock']<=0?'out':'low' ?>'><td><?=e($i['item_description'])?></td><td><?=$i['stock']?></td></tr><?php endwhile; ?></table></div></div></div></div>
<script>window.chartData={labels:<?=json_encode(array_reverse($labels))?>,received:<?=json_encode(array_map(fn($m)=>(int)($rec[$m]??0),array_reverse($labels)))?>,issued:<?=json_encode(array_map(fn($m)=>(int)($iss[$m]??0),array_reverse($labels)))?>,returned:<?=json_encode(array_map(fn($m)=>(int)($ret[$m]??0),array_reverse($labels)))?>};</script>
<script>document.addEventListener('DOMContentLoaded',()=>new Chart(document.getElementById('monthlyChart'),{type:'bar',data:{labels:chartData.labels,datasets:[{label:'Received',data:chartData.received},{label:'Issued',data:chartData.issued},{label:'Returned',data:chartData.returned}]}}));</script>
<?php include 'includes/footer.php'; ?>
