<?php require 'includes/auth.php'; require_login(); require 'config/db.php'; require 'functions.php';
$err=''; if($_SERVER['REQUEST_METHOD']==='POST'){
 foreach($_POST['item_code'] as $i=>$code){ $code=trim($code); if($code==='') continue; $qty=(int)$_POST['quantity'][$i]; $item=$conn->query("SELECT * FROM inventory_items WHERE item_code='".$conn->real_escape_string($code)."'")->fetch_assoc(); if(!$item){$err.="Item $code not found. "; continue;} if($item['actual_stock']<$qty){$err.="Insufficient stock for $code. "; continue;} add_tx($conn,'ISSUED',$code,$item['item_description'],$qty,trim($_POST['serial_number'][$i]??''),$item['location'],$item['uom'],trim($_POST['pic_receiver'][$i]),'',$_SESSION['user_id']); }
 if(!$err){header('Location: issuance.php?ok=1'); exit;}
}
include 'includes/header.php'; ?>
<h3>Issuance</h3><?php if($err) echo '<div class="alert alert-danger">'.htmlspecialchars($err).'</div>'; if(isset($_GET['ok'])) echo '<div class="alert alert-success">Issued successfully.</div>'; ?>
<div class="card p-4"><form method="post"><table class="table" id="entry"><thead><tr><th>Item Code/Serial</th><th>Qty</th><th>Serial optional</th><th>C/O Name</th><th></th></tr></thead><tbody><tr><td><input name="item_code[]" class="form-control" required></td><td><input type="number" name="quantity[]" class="form-control" value="1" min="1"></td><td><input name="serial_number[]" class="form-control"></td><td><input name="pic_receiver[]" class="form-control" required></td><td><button type="button" class="btn btn-danger del">x</button></td></tr></tbody></table><button type="button" id="add" class="btn btn-secondary">+ Add Entry</button><button class="btn btn-primary">Save All</button></form></div><script>document.addEventListener('click',e=>{if(e.target.id==='add'){let tr=document.querySelector('#entry tbody tr').cloneNode(true);tr.querySelectorAll('input').forEach(i=>i.value=i.type==='number'?1:'');document.querySelector('#entry tbody').appendChild(tr)} if(e.target.classList.contains('del')&&document.querySelectorAll('#entry tbody tr').length>1)e.target.closest('tr').remove();});</script>
<?php include 'includes/footer.php'; ?>
