<?php include 'includes/header.php';
$where=[]; $params=[]; $types='';
foreach(['action_type','pic','serial_number'] as $f){ if(!empty($_GET[$f])){ $where[]="$f LIKE ?"; $params[]='%'.$_GET[$f].'%'; $types.='s'; }}
if(!empty($_GET['item'])){ $where[]='item_description LIKE ?'; $params[]='%'.$_GET['item'].'%'; $types.='s'; }
if(!empty($_GET['from'])){ $where[]='DATE(created_at)>=?'; $params[]=$_GET['from']; $types.='s'; } if(!empty($_GET['to'])){ $where[]='DATE(created_at)<=?'; $params[]=$_GET['to']; $types.='s'; }
$sql='SELECT * FROM transactions'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY created_at DESC'; $stmt=$conn->prepare($sql); if($params)$stmt->bind_param($types,...$params); $stmt->execute(); $res=$stmt->get_result(); $qs=http_build_query($_GET); ?>
<div class='d-flex justify-content-between mb-3'><h3>Transaction Log</h3><div class='page-actions'><?php if(is_admin()): ?><a class='btn btn-success' href='export_excel.php?type=transactions&<?=$qs?>'>Excel Export</a> <a class='btn btn-danger' href='pdf_report.php?<?=$qs?>'>PDF Report</a><?php endif; ?></div></div>
<div class='card cardx p-3 mb-3'><form class='row g-2'><div class='col-md-2'><input type='date' class='form-control' name='from' value='<?=e($_GET['from']??'')?>'></div><div class='col-md-2'><input type='date' class='form-control' name='to' value='<?=e($_GET['to']??'')?>'></div><div class='col-md-2'><select class='form-select' name='action_type'><option value=''>All Actions</option><?php foreach(['Received','Issued','Returned','Adjusted'] as $a):?><option <?=($_GET['action_type']??'')==$a?'selected':''?>><?=$a?></option><?php endforeach;?></select></div><div class='col-md-2'><input class='form-control' name='pic' placeholder='PIC' value='<?=e($_GET['pic']??'')?>'></div><div class='col-md-2'><input class='form-control' name='serial_number' placeholder='Serial / Code' value='<?=e($_GET['serial_number']??'')?>'></div><div class='col-md-2'><input class='form-control' name='item' placeholder='Item' value='<?=e($_GET['item']??'')?>'></div><div class='col-md-2'><button class='btn btn-primary w-100'>Filter</button></div></form></div>
<div class='card cardx p-3'><table class='table table-hover datatable'><thead><tr><th>ID</th><th>Date When</th><th>What / Action</th><th>Serial / Code</th><th>Item</th><th>Qty</th><th>PIC</th><th>Week</th><th>Location</th></tr></thead><tbody><?php while($r=$res->fetch_assoc()):?><tr><td><?=$r['id']?></td><td><?=e($r['created_at'])?></td><td><?=e($r['action_type'])?></td><td><?=e($r['serial_number'])?></td><td><?=e($r['item_description'])?></td><td><?=$r['quantity']?></td><td><?=e($r['pic'])?></td><td><?=e($r['week_no'])?></td><td><?=e($r['location'])?></td></tr><?php endwhile;?></tbody></table></div><?php include 'includes/footer.php'; ?>
